In [2]:
import numpy as np  
kernal_size=3;
box_blur_kernal=np.ones((kernal_size,kernal_size))/kernal_size**2;
box_blur_kernal

array([[0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111]])

In [6]:
import cv2

# Generate a 5x5 Gaussian blur kernel
kernel_size = 5
gaussian_kernel = cv2.getGaussianKernel(kernel_size, sigma=1)
gaussian_kernel = gaussian_kernel * gaussian_kernel.T  # 2D kernel
print(gaussian_kernel)


[[0.00296902 0.01330621 0.02193823 0.01330621 0.00296902]
 [0.01330621 0.0596343  0.09832033 0.0596343  0.01330621]
 [0.02193823 0.09832033 0.16210282 0.09832033 0.02193823]
 [0.01330621 0.0596343  0.09832033 0.0596343  0.01330621]
 [0.00296902 0.01330621 0.02193823 0.01330621 0.00296902]]


### **How to Generate a 2D Gaussian Blur Kernel**

This code generates a **2D Gaussian blur kernel** using OpenCV's `cv2.getGaussianKernel` function. Here's a detailed explanation:

---

### **Code Breakdown**

#### 1. **`cv2.getGaussianKernel(kernel_size, sigma=1)`**
- **Purpose**: Creates a 1D Gaussian kernel.
- **Arguments**:
  | Argument         | Description                                                                                   |
  |------------------|-----------------------------------------------------------------------------------------------|
  | `kernel_size`    | Size of the kernel (e.g., `5` for a \(5 \times 5\) kernel). Must be an odd integer.            |
  | `sigma`          | Standard deviation of the Gaussian distribution. Controls the spread of the blur.             |

- The function returns a column vector representing the 1D Gaussian kernel.


---

#### 2. **`gaussian_kernel @ gaussian_kernel.T`**
- **Purpose**: Converts the 1D kernel into a **2D Gaussian kernel**.
- **How it works**:
  - The matrix multiplication (`@`) of the 1D kernel with its transpose creates a 2D kernel.
  - This ensures the 2D Gaussian distribution is symmetric.


---

#### 3. **`print(gaussian_kernel)`**
- Prints the generated **2D Gaussian kernel** to the console.

---

### **Key Features of a Gaussian Kernel**
- **Symmetry**: Both rows and columns are symmetric around the center.
- **Normalization**: The sum of all elements equals 1. This ensures the overall brightness of the image remains unchanged.
- **Effect of `sigma`**:
  - **Small `sigma`**: The kernel is more concentrated around the center (sharp blur).
  - **Large `sigma`**: The kernel spreads out (stronger blur).

---



### **Usage**
This 2D Gaussian kernel can be used for:
1. **Gaussian Blurring**:
   - Smoothens the image while preserving edges better than a box blur.
2. **Weighting in Image Processing**:
   - Used in algorithms like Gaussian pyramids, edge detection, etc.


In [14]:
# blur kernal
kernal_size=9;
motion_blur_kernal=np.zeros((kernal_size, kernal_size))
# print(motion_blur_kernal)
motion_blur_kernal[int((kernal_size-1)/2),:]=np.ones(kernal_size)
# print(motion_blur_kernal)
motion_blur_kernal/=kernal_size;
'''is performing normalization on the
motion_blur_kernel by dividing each element
in the kernel by the kernel_size. This ensures
that the sum of all elements in the kernel is 
scaled appropriately, which is important to
maintain the brightness of the image after applying the
kernel during the convolution process.'''
motion_blur_kernal

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.11111111, 0.11111111, 0.11111111, 0.11111111, 0.11111111,
        0.11111111, 0.11111111, 0.11111111, 0.11111111],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],


In [ ]:
def apply_low_light(image, gamma=0.3):
    """
    Düşük ışık koşullarını simüle etmek için gamma düzeltmesi uygula.
    """
    inv_gamma = 1.0 / gamma
    table = np.array([((i / 255.0) ** inv_gamma) * 255 for i in range(256)]).astype("uint8")
    low_light_image = cv2.LUT(image, table)
    return low_light_image


In [16]:
gamma=0.3
inv_gamma=1/gamma
# here if gamma greater thatn 1 then image becme darker
table=np.array([((i/255)**inv_gamma )*255 for i in range(256)]).astype("uint8")



[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   1   1   1   1   1
   1   1   1   1   1   1   2   2   2   2   2   2   2   2   3   3   3   3
   3   3   4   4   4   4   4   5   5   5   5   6   6   6   6   7   7   7
   7   8   8   8   9   9   9  10  10  10  11  11  12  12  12  13  13  14
  14  15  15  15  16  16  17  17  18  18  19  20  20  21  21  22  23  23
  24  24  25  26  26  27  28  29  29  30  31  32  32  33  34  35  36  37
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  55
  56  57  58  59  60  62  63  64  66  67  68  69  71  72  74  75  76  78
  79  81  82  84  85  87  89  90  92  93  95  97  99 100 102 104 106 107
 109 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 142 144
 146 148 151 153 155 158 160 163 165 168 170 173 175 178 180 183 186 188
 191 194 196 199 202 205 208 211 214 217 220 223 22

### **`cv2.LUT()` Function**

#### **Purpose**
- `cv2.LUT()` is used to apply a lookup table (LUT) to an image for pixel-wise transformation. It replaces each pixel value in the input image with a corresponding value from the LUT.

---

#### **Arguments**
| Argument   | Type             | Description                                                                 |
|------------|------------------|-----------------------------------------------------------------------------|
| `image`    | `numpy.ndarray`  | Input image to which the transformation is applied.                        |
| `table`    | `numpy.ndarray`  | Lookup table containing the new values for pixel intensities (size = 256). |

---

#### **Return Type**
- **`numpy.ndarray`**: The transformed image with the same dimensions as the input image, where each pixel value is replaced based on the lookup table.

---

#### **What It Does**
1. Takes an image and a lookup table as input.
2. For each pixel in the image:
   - Finds its intensity value.
   - Replaces it with the corresponding value from the lookup table.
3. Returns the transformed image.

---

#### **Example**
```python
import cv2
import numpy as np

# Create a lookup table (e.g., invert pixel values)
lookup_table = np.array([255 - i for i in range(256)], dtype="uint8")

# Load an image
image = cv2.imread("example.jpg")

# Apply the lookup table
transformed_image = cv2.LUT(image, lookup_table)

# Display the result
cv2.imshow("Transformed Image", transformed_image)
cv2.waitKey(0)
cv2.destroyAllWindows()
```

---

